apiVersion: v1
kind: Pod
metadata:
  name: 
  labels:
    name: 
spec:
  containers:
    - name: 
      image: busybox:1.36.1
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 80