apiVersion: apps/v1
kind: Deployment 
metadata:
  name: color-api 
spec:
  selector:
    matchLabels:
        app: color-api 
        environment: local
        tier: backend
    matchExpressions: 
      - key: release
        operator: NotIn
        values: 
          - canary
  template: 
    metadata:

    
      labels:
        app: color-api 
        environment: local
        tier: backend
        release: stable
    spec: 
      containers:
        - name: color-api
          image: lmacademy/color-api:1.1.0
          ports: 
            - containerPort: 80