apiVersion: v1 
kind: Pod 
metadata:
  name: nginx-pod
  labels: 
    app: nginx 
  annotations:
    description: "Nginx pod for learning purposes"
spec:
  containers:
  - image: nginx:1.27.0-alpine
    name: nginx-container 
    ports:
    - containerPort: 80
