apiVersion: v1
kind: Pod
metadata:
  name: traffic-generator
  labels:
    name: traffic-generator
spec:
  containers:
    - name: traffic-generator
      image: lmacademy/traffic-generator:1.0.0
      args:
        - "color-api-svc/api"
        - "0.5"
      ports:
        - containerPort: 80
      resources:
        limits: 
          cpu: "500m"
          memory: "512Mi"