apiVersion: v1
kind: Pod
metadata:
  name: traffic-generator
  labels:
    app: traffic-generator 
spec:
  containers:
    - name: traffic-generator
      image: lmacademy/color-api:1.0.0
      args:
        - "color-api-svc.dev.svc.cluster.local/api"
        - "1"